export const INIT_USER_INFOR = "INIT_USER_INFOR";

// postDetailsReducers
export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAILURE = "POST_DETAILS_FAILURE";

// postCreateReducers
export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE";
export const POST_CREATE_RESET = "POST_CREATE_RESET";

// favoriteCreateReducer
export const FAVORITE_CREATE_REQUEST = "FAVORITE_CREATE_REQUEST";
export const FAVORITE_CREATE_SUCCESS = "FAVORITE_CREATE_SUCCESS";
export const FAVORITE_CREATE_FAILURE = "FAVORITE_CREATE_FAILURE";
export const FAVORITE_CREATE_RESET = "FAVORITE_CREATE_RESET";

export const FAVORITE_DELETE_REQUEST = "FAVORITE_DELETE_REQUEST";
export const FAVORITE_DELETE_SUCCESS = "FAVORITE_DELETE_SUCCESS";
export const FAVORITE_DELETE_FAILURE = "FAVORITE_DELETE_FAILURE";
export const FAVORITE_DELETE_RESET = "FAVORITE_DELETE_RESET";

// favoriteListReducer
export const FAVORITE_LIST_REQUEST = "FAVORITE_LIST_REQUEST";
export const FAVORITE_LIST_SUCCESS = "FAVORITE_LIST_SUCCESS";
export const FAVORITE_LIST_FAILURE = "FAVORITE_LIST_FAILURE";
export const FAVORITE_LIST_RESET = "FAVORITE_LIST_RESET";
