export const CHANGE_BOOL = "CHANGE_BOOL";

export const CHANGE_COUNT = "CHANGE_COUNT";

export const INIT_USER_INFOR = "INIT_USER_INFOR";

// postDetailsReducers
export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAILURE = "POST_DETAILS_FAILURE";

// postCreateReducers
export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE";
export const POST_CREATE_RESET = "POST_CREATE_RESET";

// favoriteCreateReducer
export const FAVORITE_CREATE_REQUEST = "FAVORITE_CREATE_REQUEST";
export const FAVORITE_CREATE_SUCCESS = "FAVORITE_CREATE_SUCCESS";
export const FAVORITE_CREATE_FAILURE = "FAVORITE_CREATE_FAILURE";
export const FAVORITE_CREATE_RESET = "FAVORITE_CREATE_RESET";
